import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,Check} from 'lucide-react';
import {api,initialProfile,remember,expiredSession,forgetSession,retryable,type Profile,type Snapshot} from '../lib/api';
export default function Onboarding(){
 const [profile,setProfile]=useState<Profile>(initialProfile);const [step,setStep]=useState(0);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [editing,setEditing]=useState<string|null>(null);const [loading,setLoading]=useState(false);
 const heading=useRef<HTMLHeadingElement>(null);const editId=useRef<string|null>(null);const [expired,setExpired]=useState(false);const [loadFailed,setLoadFailed]=useState(false);const [canRetry,setCanRetry]=useState(false);
 function failed(cause:unknown){if(expiredSession(cause)){forgetSession();setEditing(null);setExpired(true);setError('Your prototype session has expired. Start a new plan or try the demo.');setCanRetry(false);}else{setError((cause as Error).message);setCanRetry(retryable(cause));}}
 async function loadAnswers(){const id=editId.current;if(!id)return;setLoading(true);setError('');setCanRetry(false);try{const s=await api<Snapshot>('/plan/'+id);setProfile(s.profile);setEditing(id);setLoadFailed(false);}catch(e){setLoadFailed(true);failed(e);}finally{setLoading(false);}}
 useEffect(()=>{if(new URLSearchParams(location.search).has('edit')){editId.current=localStorage.getItem('life-setup-profile');if(editId.current)void loadAnswers();else setExpired(true);}},[]);
 useEffect(()=>{if(!loading&&!loadFailed&&!expired)heading.current?.focus();},[step,loading,loadFailed,expired]);
 function change<K extends keyof Profile>(key:K,value:Profile[K]){setProfile(p=>({...p,[key]:value}));setError('');}
 function choice(key:keyof Profile,label:string,value:boolean){return <button type="button" aria-pressed={profile[key]===value} className={'choice '+(profile[key]===value?'selected':'')} onClick={()=>{change(key,value as never);if(key==='movingWithFamily'&&!value)change('movingWithChildren',false);}}>{label}{profile[key]===value&&<Check size={18}/>}</button>;}
 const headings=['Where are you moving from?','Who is moving with you?','How far along is your residence process?','Do you already have an Emirates ID?','Do you have a home in Abu Dhabi?','Will you drive in Abu Dhabi?','Are you bringing a pet?'];
 async function next(){
  if(step===0&&(!profile.nationality.trim()||!profile.movingFrom.trim())){setError('Tell us your nationality and where you’re moving from.');return;}
  if(step===5&&profile.wantsToDrive&&!profile.licenceCountry.trim()){setError('Enter your licence country, or “None” if you do not have one.');return;}
  if(step<6){setStep(step+1);return;}
  setBusy(true);setError('');setCanRetry(false);try{const s=await api<Snapshot>(editing?'/profile/'+editing:'/profile',profile,editing?'PUT':'POST');remember(s);location.href='/plan';}catch(e){failed(e);setBusy(false);}
 }
 if(expired)return <section className="empty-state"><h1>Let’s make a new plan.</h1><p role="alert">{error||'Your prototype session has expired. Start a new plan or try the demo.'}</p><div className="welcome-actions"><a className="button primary" href="/onboarding">Get started</a><a className="button secondary" href="/">Try the demo</a></div></section>;
 if(loadFailed&&!loading)return <section className="empty-state"><h1>Your answers are still saved.</h1><p role="alert" className="error">{error}</p>{canRetry&&<button className="button secondary" onClick={loadAnswers}>Try again</button>}<a className="text-link" href="/plan">Back to your plan</a></section>;
 return <section className="onboarding">{loading?<p role="status">Loading your answers…</p>:<><div className="step-top"><span className="eyebrow">{editing?'Update your move':'A plan that fits your move'}</span><span className="quiet">{step+1} of 7</span></div><div className="thin-progress"><div style={{width:((step+1)/7*100)+'%'}}/></div><h1 ref={heading} className="question" tabIndex={-1}>{headings[step]}</h1><p className="muted">{step===2?'Your employer may be helping with this.':step===3?'This is your UAE identity card.':'A few quick answers help us put your steps in order.'}</p><div className="question-body">
 {step===0&&<><label>Nationality<input maxLength={100} value={profile.nationality} placeholder="For example, Spanish" onChange={e=>change('nationality',e.target.value)}/></label><label>Country you’re moving from<input maxLength={100} value={profile.movingFrom} placeholder="For example, Spain" onChange={e=>change('movingFrom',e.target.value)}/></label><label>Are you already in the UAE?</label><div className="choices">{choice('alreadyInUae','Yes, I’m here',true)}{choice('alreadyInUae','Not yet',false)}</div></>}
 {step===1&&<><div className="choices">{choice('movingWithFamily','With family',true)}{choice('movingWithFamily','On my own',false)}</div>{profile.movingWithFamily&&<><label>Are children moving with you?</label><div className="choices">{choice('movingWithChildren','Yes',true)}{choice('movingWithChildren','No',false)}</div></>}</>}
 {step===2&&<div className="choices vertical">{(['NOT_STARTED','IN_PROGRESS','COMPLETE'] as const).map((v,i)=><button key={v} className={'choice '+(profile.residenceStatus===v?'selected':'')} onClick={()=>{change('residenceStatus',v);if(v!=='COMPLETE')change('hasEmiratesId',false);}}>{['Not started','My residence process is underway','My residence is complete'][i]}{profile.residenceStatus===v&&<Check size={18}/>}</button>)}</div>}
 {step===3&&<><div className="choices"><button className={'choice '+(profile.hasEmiratesId?'selected':'')} onClick={()=>{change('hasEmiratesId',true);change('residenceStatus','COMPLETE');}}>Yes, I have it {profile.hasEmiratesId&&<Check size={18}/>}</button>{choice('hasEmiratesId','Not yet',false)}</div><p className="quiet">If you have your card, we record the related residence milestone as complete.</p></>}
 {step===4&&<div className="choices">{choice('hasHousing','Yes, I have a home',true)}{choice('hasHousing','I’m still looking',false)}</div>}
 {step===5&&<><div className="choices">{choice('wantsToDrive','Yes',true)}{choice('wantsToDrive','No',false)}</div>{profile.wantsToDrive&&<label>Which country issued your driving licence?<input maxLength={100} value={profile.licenceCountry} placeholder="Country, or None" onChange={e=>change('licenceCountry',e.target.value)}/><span className="quiet">The official service will confirm your options.</span></label>}</>}
 {step===6&&<div className="choices">{choice('bringingPet','Yes',true)}{choice('bringingPet','No',false)}</div>}
 </div>{error&&<div className="error" role="alert"><p>{error}</p>{canRetry&&<button className="text-link" disabled={busy} onClick={next}>Try again</button>}</div>}<div className="onboarding-nav"><button className="button text" disabled={busy} onClick={()=>step?setStep(step-1):location.assign(editing?'/plan':'/')}><ArrowLeft size={16}/>Back</button><button className="button primary" disabled={busy} onClick={next}>{busy?'Saving your plan…':step===6?'See my plan':'Continue'}<ArrowRight size={16}/></button></div></>}</section>;
}
